services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: sync+restart
          path: internal
          target: /code/internal
        - action: sync+restart
          path: cmd
          target: /code/cmd
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy